version: '3.8'

services:
  todo_backend_prod:
    image: backend-todo-img
    container_name: todo_backend
    build:
      context: .
      dockerfile: ./todo-backend/Dockerfile
    depends_on:
      - redis_prod
      - mongo_prod
    command: sh -c "npm install && npm start"
    volumes:
      - ./todo-backend/:/usr/src/app
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis_prod
      - MONGO_URL=mongodb://the_username:the_password@mongo_prod:27017/the_database
  mongo_prod:
    image: mongo
    container_name: mongo_prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data_prod:/data/db
  redis_prod:
    image: redis
    container_name: redis_prod
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
    - ./redis_data_prod:/data

  nginx:
      image: prod-nginx-img
      container_name: prod-nginx
      build:
        context: .
        dockerfile: ./todo-frontend/Dockerfile.prodnginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 8080:80
      depends_on:
        - todo_backend_prod
volumes:
  mongo_data_prod:
