FROM  node:16 AS build-stage

WORKDIR /usr/src/app

COPY . .

RUN npm ci

ENV PORT=3001

ENV REACT_APP_BACKEND_URL=http://localhost:8080/api

RUN CI=true npm test

RUN npm run build

FROM nginx:latest

WORKDIR /etc/nginx/html

COPY --from=build-stage /usr/src/app/build .