services:
  note_db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - notes-pg-data:/var/lib/postgresql/data
volumes:
  notes-pg-data: